### PR TITLE
Fix parsing of due dates with time

### LINKED ISSUE #24: Start date based on due date broken when due date has time specified
I have a recurring task due every Tuesday at 22:00. I defined start date as ‘start=due-0d’. It’s still labeled as next action, it shouldn’t because today is Sunday.

When 22:00 is removed from the task the task is correctly not labeled

### PR DESCRIPTION
**Pull request by RoccoMathijn**
Now it works for both due dates without time (2016-12-16) and due dates with time (2016-12-01T12:00:00)

Fixes https://github.com/Hoffelhas/autodoist/issues/24

Edit: Added some more functionality to take timezones into account

### CODE REVIEW

**Comment by erauner12** [comment]
Im have -nf set to 3 days. And still having trouble with next action label getting applied with tasks that are due in the future

**Comment by RoccoMathijn** [comment]
> Im have -nf set to 3 days. And still having trouble with next action label getting applied with tasks that are due in the future

Is that with my new proposed code?

**Comment by erauner12** [comment]
Yes I was still having issue unfortunately. I can try and re-create to give more info

**Comment by RoccoMathijn** [comment]
@erauner12 I think your issue is something different than what this PR fixes: https://github.com/Hoffelhas/autodoist/issues/24

This is about start dates not the due dates too far in the future.

The docs talk about parameter `-hf` while you say `-nf`. Did you make a typo or is that the problem perhaps?

**Comment by Hoffelhas** [comment]
Thanks for writing a fix for this. Can't be merged in the latest dev version, but has been included manually.

**Pull request closed without merging**
